export const pokemonDb = () => {
    return [
        {
            name: "Bulbasaur",
            number: 1,
            gender: "Masculino",
            imageUrl: "https://archives.bulbagarden.net/media/upload/f/fb/0001Bulbasaur.png",
            type: ["Planta", "Veneno"],
            weight: 6.9,
            abilities: ["Espesura", "Clorofila"],
            hp: 45,
            def: 49,
            atk: 49,
            spdf: 65,
            spatk: 65,
            spd: 45,
            dummy: true,
            weaknesses: ["Fuego", "Psíquico", "Hielo"],
        },
        
        {
            name: "Charmander",
            number: 4,
            gender: "Femenino",
            imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png",
            type: ["Fuego"],
            weight: 8.5,
            abilities: ["Mar Llamas", "Poder Solar"],
            hp: 39,
            def: 43,
            atk: 52,
            spdf: 50,
            spatk: 60,
            spd: 65,
            dummy: true,
            weaknesses: ["Agua", "Tierra", "Roca"],
        },
        {
            name: "Squirtle",
            number: 7,
            gender: "Masculino",
            imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png",
            type: ["Agua"],
            weight: 9,
            abilities: ["Torrente", "Caparazón"],
            hp: 44,
            def: 65,
            atk: 48,
            spdf: 64,
            spatk: 50,
            spd: 43,
            dummy: true,
            weaknesses: ["Eléctrico", "Planta"],
        },
        
        {
            name: "Pikachu",
            number: 25,
            gender: "Femenino",
            imageUrl: "https://upload.wikimedia.org/wikipedia/en/a/a6/Pok%C3%A9mon_Pikachu_art.png",
            type: ["Eléctrico"],
            weight: 6,
            abilities: ["Electricidad Estática", "Pararrayos"],
            hp: 35,
            def: 40,
            atk: 55,
            spdf: 50,
            spatk: 50,
            spd: 90,
            dummy: true,
            weaknesses: ["Tierra"],
        },
        
        {
            name: "Jigglypuff",
            number: 39,
            gender: "Femenino",
            imageUrl: "https://upload.wikimedia.org/wikipedia/en/2/22/Pok%C3%A9mon_Jigglypuff_art.png",
            type: ["Hada", "Normal"],
            weight: 5.5,
            abilities: ["Voz Dulce", "Gran Encanto"],
            hp: 115,
            def: 20,
            atk: 45,
            spdf: 25,
            spatk: 45,
            spd: 20,
            dummy: true,
            weaknesses: ["Acero", "Veneno"],
        },
        
        {
            name: "Eevee",
            number: 133,
            gender: "Masculino",
            imageUrl: "https://upload.wikimedia.org/wikipedia/en/a/a9/Pok%C3%A9mon_Eevee_art.png",
            type: ["Normal"],
            weight: 6.5,
            abilities: ["Adaptable", "Anticipación"],
            hp: 55,
            def: 50,
            atk: 55,
            spdf: 65,
            spatk: 45,
            spd: 55,
            dummy: true,
            weaknesses: ["Lucha"],
        },
        
        {
            name: "Snorlax",
            number: 143,
            gender: "Masculino",
            imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/143.png",
            type: ["Normal"],
            weight: 460,
            abilities: ["Inmunidad", "Sebo"],
            hp: 160,
            def: 65,
            atk: 110,
            spdf: 65,
            spatk: 65,
            spd: 30,
            dummy: true,
            weaknesses: ["Lucha"],
        },
        
        {
            name: "Dragonite",
            number: 149,
            gender: "Femenino",
            imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/149.png",
            type: ["Dragón", "Volador"],
            weight: 210,
            abilities: ["Velo Arena", "Entusiasmo"],
            hp: 91,
            def: 95,
            atk: 134,
            spdf: 100,
            spatk: 100,
            spd: 80,
            dummy: true,
            weaknesses: ["Hielo", "Hada", "Roca"],
        },
        
        {
            name: "Mewtwo",
            number: 150,
            gender: "Masculino",
            imageUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/150.png",
            type: ["Psíquico"],
            weight: 122,
            abilities: ["Presión", "Despiste"],
            hp: 106,
            def: 90,
            atk: 110,
            spdf: 154,
            spatk: 154,
            spd: 130,
            dummy: true,
            weaknesses: ["Bicho", "Fantasma", "Siniestro"],
        },
        
        {
            name: "Mew",
            number: 151,
            gender: "Femenino",
            imageUrl: "https://upload.wikimedia.org/wikipedia/en/4/4b/Pok%C3%A9mon_Mew_art.png",
            type: ["Psíquico"],
            weight: 4,
            abilities: ["Sincronía"],
            hp: 100,
            def: 100,
            atk: 100,
            spdf: 100,
            spatk: 100,
            spd: 100,
            dummy: true,
            weaknesses: ["Bicho", "Fantasma", "Siniestro"],
        },
    ]
}